"use client";

import { useEffect, useState } from "react";

export interface CommitteePost {
  postId?: string;
  postTitle: string;
  user_posts?: {
    user?: {
      name?: string;
    };
  }[];
}

export interface CommitteeOption {
  committeeId?: string;
  type: string;
  year: number;
  status: string;
  posts: CommitteePost[];
}

interface CreateUserModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreated?: () => void;
  onSuccess?: () => void;
}

const ROLES_REQUIRING_POST = ["ADMIN", "MODERATOR"];

const INITIAL_FORM_STATE = {
  userId: "",
  name: "",
  email: "",
  role: "MEMBER",
  selectedCommitteeKey: "", // format: "TYPE|YEAR" e.g. "EXECUTIVE|2027"
  postMode: "new" as "existing" | "new",
  existingPostTitle: "",
  newPostTitle: "",
};

export default function CreateUserModal({
  isOpen,
  onClose,
  onCreated,
  onSuccess,
}: CreateUserModalProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [committees, setCommittees] = useState<CommitteeOption[]>([]);
  const [form, setForm] = useState(INITIAL_FORM_STATE);

  const requiresPost = ROLES_REQUIRING_POST.includes(form.role);

  useEffect(() => {
    if (!isOpen) {
      setForm(INITIAL_FORM_STATE);
      setError(null);
      return;
    }

    fetch("/api/committees")
      .then((res) => res.json())
      .then((json) => {
        if (json.success && Array.isArray(json.data)) {
          const activeCommittees: CommitteeOption[] = json.data.filter(
            (c: CommitteeOption) => c.status === "ACTIVE"
          );
          setCommittees(activeCommittees);

          if (activeCommittees.length === 1) {
            const single = activeCommittees[0];
            setForm((prev) => ({
              ...prev,
              selectedCommitteeKey: `${single.type}|${single.year}`,
            }));
          }
        }
      })
      .catch((err) => console.error("Failed to load committees:", err));
  }, [isOpen]);
  useEffect(() => {
    if (!requiresPost) {
      setForm((f) => ({
        ...f,
        selectedCommitteeKey: "",
        existingPostTitle: "",
        newPostTitle: "",
        postMode: "new",
      }));
    }
  }, [requiresPost]);

  if (!isOpen) return null;

  // সিলেক্ট করা টাইপ ও ইয়ার ফিল্টার
  const [selectedType, selectedYearStr] = form.selectedCommitteeKey.split("|");
  const selectedYear = selectedYearStr ? parseInt(selectedYearStr, 10) : null;

  const selectedCommittee = committees.find(
    (c) => c.type === selectedType && c.year === selectedYear
  );

  const generateRandomPassword = (length = 12) => {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
    let password = "";
    for (let i = 0; i < length; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return password;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (requiresPost) {
      if (!form.selectedCommitteeKey) {
        setError("Admin and Moderator accounts must be assigned to a committee.");
        return;
      }
      if (form.postMode === "new" && !form.newPostTitle) {
        setError("Enter a post title to create for this member.");
        return;
      }
      if (form.postMode === "existing" && !form.existingPostTitle) {
        setError("Select an existing post to assign.");
        return;
      }
    }

    setLoading(true);
    try {
      let realCommitteeId = "";
      let realExistingPostId = "";

      // 🔍 ১. টাইপ এবং ইয়ার দিয়ে আসল Database committeeId খুঁজে বের করা
      if (requiresPost && selectedType && selectedYear) {
        const lookupRes = await fetch(
          `/api/committees/lookup?type=${selectedType}&year=${selectedYear}`
        );
        const lookupData = await lookupRes.json();

        if (!lookupRes.ok || !lookupData.committeeId) {
          throw new Error("Could not find database ID for selected committee.");
        }
        realCommitteeId = lookupData.committeeId;

        // 🔍 ২. Existing Post সিলেক্ট করা থাকলে সেটির আসল postId খোঁজা
        if (form.postMode === "existing" && form.existingPostTitle) {
          const matchedPost = lookupData.posts?.find(
            (p: any) => p.postTitle === form.existingPostTitle
          );
          if (matchedPost) {
            realExistingPostId = matchedPost.postId;
          }
        }
      }

      const autoGeneratedPassword = generateRandomPassword(12);

      const payload = {
        userId: form.userId,
        name: form.name,
        email: form.email,
        password: autoGeneratedPassword,
        role: form.role,
        isCommitteeMember: requiresPost,
        ...(requiresPost && {
          committeeId: realCommitteeId, // 👈 DB real UUID
          postMode: form.postMode,
          newPostTitle: form.newPostTitle,
          existingPostId: realExistingPostId,
        }),
      };

      const res = await fetch("/api/users/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.message || "Failed to create user");

      if (onCreated) onCreated();
      if (onSuccess) onSuccess();
      onClose();
    } catch (err: any) {
      setError(err.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-xs">
      <div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-(--card-bg) p-6 shadow-xl border border-(--btn-secondary-border) sm:p-8">
        <div className="flex items-center justify-between border-b border-(--btn-secondary-border) pb-4">
          <h2 className="text-lg font-bold text-(--text-primary)">
            Create New User
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-(--text-secondary) hover:bg-(--stat-card-bg) hover:text-(--text-primary) transition-colors cursor-pointer"
          >
            ✕
          </button>
        </div>

        <form onSubmit={handleSubmit} className="mt-6 space-y-4">
          {error && (
            <div className="rounded-xl border border-(--text-important)/30 bg-(--text-important)/10 p-3 text-xs font-medium text-(--text-important)">
              {error}
            </div>
          )}

          <div>
            <label className="block text-xs font-semibold text-(--text-primary) mb-1">
              User ID / Student ID
            </label>
            <input
              type="text"
              required
              placeholder="e.g. 2023001"
              value={form.userId}
              onChange={(e) => setForm({ ...form, userId: e.target.value })}
              className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-(--text-primary) mb-1">
              Full Name
            </label>
            <input
              type="text"
              required
              placeholder="Full Name"
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
              className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-(--text-primary) mb-1">
              Email
            </label>
            <input
              type="email"
              required
              placeholder="user@neu.ac.bd"
              value={form.email}
              onChange={(e) => setForm({ ...form, email: e.target.value })}
              className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-(--text-primary) mb-1">
              Role
            </label>
            <select
              value={form.role}
              onChange={(e) => setForm({ ...form, role: e.target.value })}
              className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden cursor-pointer"
            >
              <option value="MEMBER">Member</option>
              <option value="MODERATOR">Moderator</option>
              <option value="ADMIN">Admin</option>
            </select>
          </div>

          {requiresPost && (
            <div className="space-y-3 rounded-xl border border-(--btn-primary-bg)/30 bg-(--badge-bg) p-3.5">
              <p className="text-[11px] font-semibold text-(--btn-primary-bg)">
                Required — {form.role === "ADMIN" ? "Admin" : "Moderator"} accounts must hold a committee post
              </p>

              <div>
                <label className="block text-xs font-semibold text-(--text-primary) mb-1">
                  Committee
                </label>
                
                {committees.length === 1 ? (
                  <div className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) p-2.5 text-xs text-(--text-primary) font-medium">
                    {`The ${committees[0].type} Committee-${committees[0].year}`}
                  </div>
                ) : (
                  <select
                    required
                    value={form.selectedCommitteeKey}
                    onChange={(e) =>
                      setForm({
                        ...form,
                        selectedCommitteeKey: e.target.value,
                        existingPostTitle: "",
                      })
                    }
                    className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden cursor-pointer"
                  >
                    <option value="">Select a committee</option>
                    {committees.map((c) => {
                      const key = `${c.type}|${c.year}`;
                      return (
                        <option key={key} value={key}>
                          {`The ${c.type} Committee-${c.year}`}
                        </option>
                      );
                    })}
                  </select>
                )}
              </div>

              <div className="flex gap-4 text-xs font-medium text-(--text-primary) pt-1">
                <label className="flex items-center gap-1.5 cursor-pointer">
                  <input
                    type="radio"
                    checked={form.postMode === "new"}
                    onChange={() => setForm({ ...form, postMode: "new" })}
                    className="accent-(--btn-primary-bg)"
                  />
                  Create new post
                </label>
                <label className="flex items-center gap-1.5 cursor-pointer">
                  <input
                    type="radio"
                    checked={form.postMode === "existing"}
                    onChange={() => setForm({ ...form, postMode: "existing" })}
                    className="accent-(--btn-primary-bg)"
                  />
                  Assign existing post
                </label>
              </div>

              {form.postMode === "new" ? (
                <input
                  type="text"
                  required
                  placeholder="e.g. Vice President"
                  value={form.newPostTitle}
                  onChange={(e) =>
                    setForm({ ...form, newPostTitle: e.target.value })
                  }
                  className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--card-bg) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden"
                />
              ) : (
                <select
                  required
                  value={form.existingPostTitle}
                  onChange={(e) =>
                    setForm({ ...form, existingPostTitle: e.target.value })
                  }
                  className="w-full rounded-xl border border-(--btn-secondary-border) bg-(--card-bg) p-2.5 text-xs text-(--text-primary) focus:border-(--btn-primary-bg) focus:outline-hidden cursor-pointer"
                >
                  <option value="">Select a post to reassign</option>
                  {selectedCommittee?.posts.map((p, idx) => {
                    const currentUser = p.user_posts?.[0]?.user?.name || "Unassigned";
                    return (
                      <option key={idx} value={p.postTitle}>
                        {p.postTitle} (currently: {currentUser})
                      </option>
                    );
                  })}
                </select>
              )}
            </div>
          )}

          <div className="flex justify-end gap-3 pt-4 border-t border-(--btn-secondary-border)">
            <button
              type="button"
              onClick={onClose}
              disabled={loading}
              className="rounded-xl border border-(--btn-secondary-border) bg-(--bg-app) px-4 py-2 text-xs font-semibold text-(--text-primary) hover:bg-(--stat-card-bg) transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="rounded-xl bg-(--btn-primary-bg) px-5 py-2 text-xs font-semibold text-(--btn-primary-text) shadow-xs hover:opacity-90 disabled:opacity-50 transition-opacity cursor-pointer"
            >
              {loading ? "Creating..." : "Create User"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}