"use client";

import { useEffect, useState } from "react";



export interface CommitteePost {
  postId: string;
  postTitle: string;
  // Prisma relation অনুযায়ী single user অথবা multiple relation type যুক্ত করুন:
  user?: {
    userId: string;
    name: string;
    email?: string;
  } | null;
  users?: {
    userId?: string;
    name?: string;
    email?: string;
  } | null;
  user_posts?: {
    user?: {
      name?: string;
    };
  }[];
}

export interface CommitteeOption {
  id?: string;
  type: string;
  year: number;
  status: string;
  posts: CommitteePost[];
}
interface CreateUserModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreated?: () => void;
  onSuccess?: () => void;
}

const ROLES_REQUIRING_POST = ["ADMIN", "MODERATOR"];

const INITIAL_FORM_STATE = {
  userId: "",
  name: "",
  email: "",
  role: "MEMBER",
  committeeId: "",
  postMode: "new" as "existing" | "new",
  existingPostId: "",
  newPostTitle: "",
};

export default function CreateUserModal({
  isOpen,
  onClose,
  onCreated,
  onSuccess,
}: CreateUserModalProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [committees, setCommittees] = useState<CommitteeOption[]>([]);
  const [form, setForm] = useState(INITIAL_FORM_STATE);

  const requiresPost = ROLES_REQUIRING_POST.includes(form.role);

  useEffect(() => {
    if (!isOpen) {
      setForm(INITIAL_FORM_STATE);
      setError(null);
      return;
    }

    fetch("/api/committees")
      .then((res) => res.json())
      .then((json) => {
        if (json.success && Array.isArray(json.data)) {
          const activeCommittees: CommitteeOption[] = json.data.filter(
            (c: CommitteeOption) => c.status === "ACTIVE"
          );
          setCommittees(activeCommittees);

          if (activeCommittees.length === 1) {
            const single = activeCommittees[0];
            const cId = single.id || `${single.type}-${single.year}`;
            setForm((prev) => ({ ...prev, committeeId: cId }));
          }
        }
      })
      .catch((err) => console.error("Failed to load committees:", err));
  }, [isOpen]);

  useEffect(() => {
    if (!requiresPost) {
      setForm((f) => ({
        ...f,
        committeeId: "",
        existingPostId: "",
        newPostTitle: "",
        postMode: "new",
      }));
    }
  }, [requiresPost]);

  if (!isOpen) return null;

  const selectedCommittee = committees.find(
    (c) => (c.id || `${c.type}-${c.year}`) === form.committeeId
  );
const generateRandomPassword = (length = 12) => {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
  let password = "";
  for (let i = 0; i < length; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
};
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (requiresPost) {
      if (!form.committeeId) {
        setError("Admin and Moderator accounts must be assigned to a committee.");
        return;
      }
      if (form.postMode === "new" && !form.newPostTitle) {
        setError("Enter a post title to create for this member.");
        return;
      }
      if (form.postMode === "existing" && !form.existingPostId) {
        setError("Select an existing post to assign.");
        return;
      }
    }

    setLoading(true);
    try {
      let resolvedPostTitle = "";
      if (requiresPost) {
        if (form.postMode === "new") {
          resolvedPostTitle = form.newPostTitle;
        } else {
          const foundPost = selectedCommittee?.posts.find(
            (p) => (p.postId || p.postTitle) === form.existingPostId
          );
          resolvedPostTitle = foundPost ? foundPost.postTitle : form.existingPostId;
        }
      }
const autoGeneratedPassword = generateRandomPassword(12);
      // Exact Payload Construction for API
      const payload = {
        adminUserId: form.userId,
        adminName: form.name,
        adminEmail: form.email,
        password: autoGeneratedPassword,
        role: form.role,
        isCommitteeMember: requiresPost,
        ...(requiresPost && {
          committeeId: selectedCommittee?.id || form.committeeId,
          type: selectedCommittee?.type,
          year: selectedCommittee?.year,
          postTitle: resolvedPostTitle,
        }),
      };

      const res = await fetch("/api/users/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.message || "Failed to create user");

      if (onCreated) onCreated();
      if (onSuccess) onSuccess();
      onClose();
    } catch (err: any) {
      setError(err.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-xs">
      <div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-[var(--card-bg)] p-6 shadow-xl border border-[var(--btn-secondary-border)] sm:p-8">
        <div className="flex items-center justify-between border-b border-[var(--btn-secondary-border)] pb-4">
          <h2 className="text-lg font-bold text-[var(--text-primary)]">
            Create New User
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-[var(--text-secondary)] hover:bg-[var(--stat-card-bg)] hover:text-[var(--text-primary)] transition-colors cursor-pointer"
          >
            ✕
          </button>
        </div>

        <form onSubmit={handleSubmit} className="mt-6 space-y-4">
          {error && (
            <div className="rounded-xl border border-[var(--text-important)]/30 bg-[var(--text-important)]/10 p-3 text-xs font-medium text-[var(--text-important)]">
              {error}
            </div>
          )}

          {/* User ID / Student ID Input */}
          <div>
            <label className="block text-xs font-semibold text-[var(--text-primary)] mb-1">
              User ID / Student ID
            </label>
            <input
              type="text"
              required
              placeholder="e.g. 2023001"
              value={form.userId}
              onChange={(e) => setForm({ ...form, userId: e.target.value })}
              className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-[var(--text-primary)] mb-1">
              Full Name
            </label>
            <input
              type="text"
              required
              placeholder="Full Name"
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
              className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-[var(--text-primary)] mb-1">
              Email
            </label>
            <input
              type="email"
              required
              placeholder="user@neu.ac.bd"
              value={form.email}
              onChange={(e) => setForm({ ...form, email: e.target.value })}
              className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-[var(--text-primary)] mb-1">
              Role
            </label>
            <select
              value={form.role}
              onChange={(e) => setForm({ ...form, role: e.target.value })}
              className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden cursor-pointer"
            >
              <option value="MEMBER">Member</option>
              <option value="MODERATOR">Moderator</option>
              <option value="ADMIN">Admin</option>
            </select>
          </div>

          {/* Committee post section — only shown for Admin/Moderator */}
          {requiresPost && (
            <div className="space-y-3 rounded-xl border border-[var(--btn-primary-bg)]/30 bg-[var(--badge-bg)] p-3.5">
              <p className="text-[11px] font-semibold text-[var(--btn-primary-bg)]">
                Required — {form.role === "ADMIN" ? "Admin" : "Moderator"} accounts must hold a committee post
              </p>

              <div>
                <label className="block text-xs font-semibold text-[var(--text-primary)] mb-1">
                  Committee
                </label>
                
                {committees.length === 1 ? (
                  <div className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] p-2.5 text-xs text-[var(--text-primary)] font-medium">
                    {`The ${committees[0].type} Committee-${committees[0].year}`}
                  </div>
                ) : (
                  <select
                    required
                    value={form.committeeId}
                    onChange={(e) =>
                      setForm({
                        ...form,
                        committeeId: e.target.value,
                        existingPostId: "",
                      })
                    }
                    className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden cursor-pointer"
                  >
                    <option value="">Select a committee</option>
                    {committees.map((c) => {
                      const cId = c.id || `${c.type}-${c.year}`;
                      return (
                        <option key={cId} value={cId}>
                          {`The ${c.type} Committee-${c.year}`}
                        </option>
                      );
                    })}
                  </select>
                )}
              </div>

              <div className="flex gap-4 text-xs font-medium text-[var(--text-primary)] pt-1">
                <label className="flex items-center gap-1.5 cursor-pointer">
                  <input
                    type="radio"
                    checked={form.postMode === "new"}
                    onChange={() => setForm({ ...form, postMode: "new" })}
                    className="accent-[var(--btn-primary-bg)]"
                  />
                  Create new post
                </label>
                <label className="flex items-center gap-1.5 cursor-pointer">
                  <input
                    type="radio"
                    checked={form.postMode === "existing"}
                    onChange={() => setForm({ ...form, postMode: "existing" })}
                    className="accent-[var(--btn-primary-bg)]"
                  />
                  Assign existing post
                </label>
              </div>

              {form.postMode === "new" ? (
                <input
                  type="text"
                  required
                  placeholder="e.g. Vice President"
                  value={form.newPostTitle}
                  onChange={(e) =>
                    setForm({ ...form, newPostTitle: e.target.value })
                  }
                  className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--card-bg)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden"
                />
              ) : (
                <select
                  required
                  value={form.existingPostId}
                  onChange={(e) =>
                    setForm({ ...form, existingPostId: e.target.value })
                  }
                  className="w-full rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--card-bg)] p-2.5 text-xs text-[var(--text-primary)] focus:border-[var(--btn-primary-bg)] focus:outline-hidden cursor-pointer"
                >
                  <option value="">Select a post to reassign</option>
                  {selectedCommittee?.posts.map((p, index) => {
                    const currentUser = p.user_posts?.[0]?.user?.name || "—";
                    const pKey = p.postId || `post-${index}`;
                    return (
                      <option key={pKey} value={p.postId || p.postTitle}>
                        {p.postTitle} (currently: {currentUser})
                      </option>
                    );
                  })}
                </select>
              )}
            </div>
          )}

          <div className="flex justify-end gap-3 pt-4 border-t border-[var(--btn-secondary-border)]">
            <button
              type="button"
              onClick={onClose}
              disabled={loading}
              className="rounded-xl border border-[var(--btn-secondary-border)] bg-[var(--bg-app)] px-4 py-2 text-xs font-semibold text-[var(--text-primary)] hover:bg-[var(--stat-card-bg)] transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="rounded-xl bg-[var(--btn-primary-bg)] px-5 py-2 text-xs font-semibold text-[var(--btn-primary-text)] shadow-xs hover:opacity-90 disabled:opacity-50 transition-opacity cursor-pointer"
            >
              {loading ? "Creating..." : "Create User"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}