import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import { z } from "zod";

// Zod Schema Definition
const membershipSchema = z.object({
  userId: z.string().trim().min(1, "User ID is required"),
  name: z.string().trim().min(2, "Name must be at least 2 characters long"),
  email: z.string().trim().email("Invalid email format"),
  session: z
    .string()
    .trim()
    .regex(/^\d{4}-\d{2}$/, "Invalid session format. Example: 2022-23"),
});

export async function POST(req: Request) {
  try {
    const body = await req.json();

    // ১. Zod Validation Check
    const validationResult = membershipSchema.safeParse(body);

    if (!validationResult.success) {
      const formattedErrors = validationResult.error.issues.map((issue) => ({
        field: issue.path[0],
        message: issue.message,
      }));

      return NextResponse.json(
        {
          success: false,
          error: validationResult.error.issues[0].message, // First error message for simple UI toast
          errors: formattedErrors,
        },
        { status: 400 }
      );
    }

    const { userId, name, email, session } = validationResult.data;

    // ২. ইউনিক চেক (userId ও email)
    const existingUser = await prisma.user.findFirst({
      where: {
        OR: [{ userId }, { email: email.toLowerCase() }],
      },
    });

    if (existingUser) {
      return NextResponse.json(
        {
          success: false,
          error:
            existingUser.userId === userId
              ? "User ID already exists"
              : "Email already registered",
        },
        { status: 400 }
      );
    }

    // ৩. হিডেন অটো পাসওয়ার্ড জেনারেশন ও হ্যাশিং
    const autoGeneratedPassword = crypto.randomBytes(16).toString("hex");
    const hashedPassword = await bcrypt.hash(autoGeneratedPassword, 10);

    // ৪. ডাটাবেজে ইউজার এনট্রি তৈরি
    const newUser = await prisma.user.create({
      data: {
        userId,
        name,
        email: email.toLowerCase(),
        password: hashedPassword,
        session,
        role: "MEMBER",
        status: "DEACTIVATED",
      },
      select: {
        userId: true,
        name: true,
        email: true,
        session: true,
        role: true,
        status: true,
        createdAt: true,
      },
    });

    return NextResponse.json(
      {
        success: true,
        message: "Membership request submitted successfully",
        data: newUser,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Membership registration error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to process membership request" },
      { status: 500 }
    );
  }
}